### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'layers'

### ISSUE THREAD

**Issue by cath0n** [philipperemy/cond_rnn#4]
Hi!

I'm trying to use cond_rnn in my project and faced an AttributeError when intialize ConditionalRNN:

outputs = ConditionalRNN(units=NUM_CELLS, cell='LSTM', cond=cond_list, activation='relu')(inputs)

Here's an error code
WARNING:tensorflow:From C:\Users\nosova.ea\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-534dd26d4757> in <module>()
----> 1 outputs = ConditionalRNN(units=NUM_CELLS, cell='LSTM', cond=cond_list, activation='relu')(inputs)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\cond_rnn\cond_rnn.py in __init__(self, units, cell, cond, *args, **kwargs)
     40             for cond in cond:
     41                 init_state_list.append(tf.keras.layers.Dense(units=units)(cond))
---> 42             multi_cond_projector = tf.layers.Dense(1, activation=None, use_bias=True)
     43             multi_cond_state = multi_cond_projector(tf.stack(init_state_list, axis=-1))
     44             multi_cond_state = tf.squeeze(multi_cond_state, axis=-1)

AttributeError: module 'tensorflow' has no attribute 'layers'

**Comment by philipperemy** [comment]
@cath0n can you provide a small snippet to reproduce the error? Also which version of tensorflow are you using?

**Comment by philipperemy** [comment]
But my guess would be that it would work with tensorflow 1.14 or tensorflow 1.15 and that you're using tensorflow 2.0.

**Comment by cath0n** [comment]
@philipperemy Yes I'm using tf 2.0. Would you mind if I'll rewrite your code for that version and commit it in your repositoty?

**Comment by philipperemy** [comment]
@cath0n yes please go ahead! That'd be great :)

**Comment by philipperemy** [comment]
@cath0n could you make any progress here?

**Comment by philipperemy** [comment]
https://github.com/philipperemy/cond_rnn/commit/be1e97fa74ee06ef44e6dec1de8eb662b63004b9 done
